version: '2'
services:
  default:
    links:
      - db:db
      - localstack:localstack
    ports:
      - 3000:3000
  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: deductions_user
      POSTGRES_DB: deductions_test
      LC_ALL: C
    ports:
      - 5432:5432
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=eu-west-2
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"