version: '2'
services:
  default:
    links:
#      - db:db
      - localstack:localstack
      - dynamodb-local:dynamodb-local
    ports:
      - 3000:3000
#  @deprecated
#  postgres db code, to be deleted in PRMT-4588
#  db:
#    image: postgres:12.1
#    environment:
#      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#      POSTGRES_USER: ${DATABASE_USER}
#      POSTGRES_DB: deductions_test
#      LC_ALL: C
#    ports:
#      - 5432:5432
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=eu-west-2
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "/var/lib/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  dynamodb-local:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "4573:8000"