version: '2'
services:
  default:
    links:
      - ehr-out-service:ehr-out-service
  ehr-out-service:
    image: ${REPOSITORY_URI}:${IMAGE_TAG}
    ports:
      - 3000:3000
    links:
#      - db:db
      - dynamodb-local:dynamodb-local
#  @deprecated
#  postgres db code, to be deleted in PRMT-4588
#  db:
#    image: postgres:12.1
#    environment:
#      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#      POSTGRES_USER: ${DATABASE_USER}
#      POSTGRES_DB: deductions_test
#      LC_ALL: C
  dynamodb-local:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "4573:8000"