version: '2'
services:
  default:
    links:
      - ehr-out-service:ehr-out-service
  ehr-out-service:
    image: ${REPOSITORY_URI}:${IMAGE_TAG}
    ports:
      - 3000:3000
    links:
      - dynamodb-local:dynamodb-local
  dynamodb-local:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "4573:8000"