version: '2'
services:
  default:
    links:
      - ehr-out-service:ehr-out-service
  ehr-out-service:
    image: ${REPOSITORY_URI}:${IMAGE_TAG}
    ports:
      - 3000:3000
    links:
      - db:db
  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: deductions_user
      POSTGRES_DB: deductions_test
      LC_ALL: C
