version: '2'
services:
  default:
    links:
      - localstack:localstack
      - dynamodb-local:dynamodb-local
    ports:
      - 3000:3000
  localstack:
    image: localstack/localstack:3.6.0
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=eu-west-2
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "/var/lib/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  dynamodb-local:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "4573:8000"