#!/usr/bin/env bash

set -Eeo pipefail

###########################
# Local Config Parameters #
###########################

AWS_DEFAULT_REGION=eu-west-2
IMAGE_REPO_NAME=deductions/repo-to-gp
export NHS_SERVICE=repo-to-gp

AWS_HELPERS_VERSION=0.2.1
AWS_HELPERS_FILE="utils/aws-helpers"

mkdir -p utils
if [[ ! -f $AWS_HELPERS_FILE ]];then
  wget --quiet -O $AWS_HELPERS_FILE https://github.com/nhsconnect/prm-deductions-support-infra/releases/download/${AWS_HELPERS_VERSION}/aws-helpers
fi
chmod +x $AWS_HELPERS_FILE
source $AWS_HELPERS_FILE

####################################
# Instance (Environment) Variables #
####################################

function check_env {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    echo "Must set NHS_ENVIRONMENT"
    exit 1
  fi
}

function check_nhs_service {
  if [[ -z "${NHS_SERVICE}" ]]; then
    echo "Must set NHS_SERVICE"
    exit 1
  fi
}

function configure_service_url {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    export SERVICE_URL=http://${NHS_SERVICE}:3000
  else
    export SERVICE_URL="https://${NHS_SERVICE}.${NHS_ENVIRONMENT}.non-prod.patient-deductions.nhs.uk"
  fi
}

function set_image_tag() {
  export IMAGE_TAG=$(git rev-parse HEAD | cut -c 1-8)
}

function prepare_local_envs_for_ide {
  export DATABASE_HOST=localhost
  envs=$( printenv | grep "DATABASE" && \
          printenv | grep "REPOSITORY_URI" && \
          printenv | grep "SERVICE_URL"
  )
  echo "Paste these env vars to your Intelij run template:"
  echo $envs | tr ' ' ';'
}

function configure_local_envs {
  export DATABASE_USER=deductions_user
  export DATABASE_PASSWORD=secret
  export DATABASE_NAME=deductions_test
  export DATABASE_HOST=db
  export GP2GP_ADAPTOR_AUTHORIZATION_KEYS=auth-key-1
  export EHR_REPO_AUTHORIZATION_KEYS=auth-key-2
  export GP2GP_ADAPTOR_SERVICE_URL="www.notreal.com"
  export EHR_REPO_SERVICE_URL="www.alsonotreal.com"
  export REPO_TO_GP_SKIP_MIGRATION=false
  export REPOSITORY_URI=$IMAGE_REPO_NAME
  configure_service_url
  set_image_tag
}

function configure_db_migration_envs {
  export REPO_TO_GP_SKIP_MIGRATION=false
  export DATABASE_HOST=$(_get_aws_ssm_secret "/repo/${NHS_ENVIRONMENT}/output/prm-deductions-repo-to-gp/db-host")
  export DATABASE_USER=$(_get_aws_ssm_secret "/repo/${NHS_ENVIRONMENT}/output/prm-deductions-repo-to-gp/db-migration-user")
  export DATABASE_NAME=$(_get_aws_ssm_secret "/repo/${NHS_ENVIRONMENT}/output/prm-deductions-repo-to-gp/db-name")
  export DATABASE_PASSWORD="$(aws rds generate-db-auth-token --hostname $DATABASE_HOST --port 5432 --region $AWS_DEFAULT_REGION --username $DATABASE_USER)"
}

function get_aws_account_id {
    AWS_ACCOUNT_ID=$(dojo -c Dojofile-infra "aws sts get-caller-identity | jq -r .Account")
}

function get_aws_ssm_secret {
   secret_id=$1
   json=$(dojo -c Dojofile-infra "aws ssm get-parameter --with-decryption --region $AWS_DEFAULT_REGION --name $secret_id")
   if [ $? != 0 ]; then
     >&2 echo "Failed to obtain AWS secret from SSM: $secret_id"
     exit 5
   fi
   echo $json | jq -r ".Parameter.Value"
}

############################
# Docker Related Functions #
############################

function docker_login {
  echo Logging in to Amazon ECR...
  eval $(dojo -c Dojofile-infra "aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION")
}

function configure_docker_repository_uri {
  docker_login
  get_aws_account_id
  export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/$IMAGE_REPO_NAME
}

function build_docker_image() {
  echo Build started on $(date)
  set_image_tag
  echo Building the Docker image...
  docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG .
  echo Build completed on `date`
}

#######################
# Terraform Functions #
#######################

function tf_init {
  check_env
  #  Condition [ $NHS_ENVIRONMENT == "test" ] is required as test environment infrastructure is deployed in CI AWS account
  [ $NHS_ENVIRONMENT == "ci" ] || [ $NHS_ENVIRONMENT == "test" ] &&  bucket_env_infix=""  || bucket_env_infix="$NHS_ENVIRONMENT-"

  cd terraform

  terraform init -reconfigure \
    -backend-config key="${NHS_SERVICE}-${NHS_ENVIRONMENT}/terraform.tfstate" \
    -backend-config bucket="prm-deductions-${bucket_env_infix}terraform-state" \
    -backend-config dynamodb_table="prm-deductions-${bucket_env_infix}terraform-table" \
    -backend-config region=${AWS_DEFAULT_REGION}
}

function tf_plan {
  operation=$1
  certs=$2
  set_image_tag
  TARGET=""


  if [[ "${certs}" == "true" ]]; then
    TARGET="-target=aws_acm_certificate.repo-to-gp-cert"
  fi

  tf_init
  terraform get # modules
  if [[ "${operation}" == "create" ]]; then
    terraform plan -var task_image_tag=$IMAGE_TAG -var-file=$NHS_ENVIRONMENT.tfvars $TARGET -out="nhs_deployment.tfplan"
  elif [[ "${operation}" == "destroy" ]]; then
    terraform plan -var task_image_tag=$IMAGE_TAG -var-file=$NHS_ENVIRONMENT.tfvars -out="nhs_deployment.tfplan" -destroy
  else
    echo "Unknown operation (should be create or destroy), got: ${operation}"
    exit 1
  fi
}

function tf_apply {
  tf_init
  terraform get # modules
  terraform apply nhs_deployment.tfplan
  terraform output -json > tf-out.json
}


function tf_init_db_roles {
  check_env
  #  Condition [ $NHS_ENVIRONMENT == "test" ] is required as test environment infrastructure is deployed in CI AWS account
  [ $NHS_ENVIRONMENT == "ci" ] || [ $NHS_ENVIRONMENT == "test" ] &&  bucket_env_infix=""  || bucket_env_infix="$NHS_ENVIRONMENT-"

  cd terraform-db-roles

  terraform init -reconfigure \
    -backend-config key="${NHS_SERVICE}-${NHS_ENVIRONMENT}-db-roles/terraform.tfstate" \
    -backend-config bucket="prm-deductions-${bucket_env_infix}terraform-state" \
    -backend-config dynamodb_table="prm-deductions-${bucket_env_infix}terraform-table" \
    -backend-config region=${AWS_DEFAULT_REGION}
}

function tf_plan_db_roles {
  operation=$1
  db_host=$(_get_aws_ssm_secret "/repo/${NHS_ENVIRONMENT}/output/prm-deductions-repo-to-gp/db-host")
  db_username=$(_get_aws_ssm_secret "/repo/${NHS_ENVIRONMENT}/user-input/repo-to-gp-db-username")
  db_password=$(_get_aws_ssm_secret "/repo/${NHS_ENVIRONMENT}/user-input/repo-to-gp-db-password")
  db_name=$(_get_aws_ssm_secret "/repo/${NHS_ENVIRONMENT}/output/prm-deductions-repo-to-gp/db-name")

  tf_init_db_roles
  terraform get # modules
  if [[ "${operation}" == "create" ]]; then
    terraform plan -var db_host=$db_host -var db_username=$db_username -var db_password=$db_password -var environment=$NHS_ENVIRONMENT -var db_name=$db_name -out="${NHS_ENVIRONMENT}-db-roles.tfplan"
  elif [[ "${operation}" == "destroy" ]]; then
    terraform plan -var db_host=$db_host -var db_username=$db_username -var db_password=$db_password -var environment=$NHS_ENVIRONMENT -var db_name=$db_name -out="${NHS_ENVIRONMENT}-db-roles.tfplan" -destroy
  else
    echo "Unknown operation (should be create or destroy), got: ${operation}"
    exit 1
  fi
}

function tf_apply_db_roles {
  tf_init_db_roles
  terraform get # modules
  terraform apply "${NHS_ENVIRONMENT}-db-roles.tfplan"
  terraform output -json > tf-out-db-roles.json
}


####################
# Script Functions #
####################

function send_canary_update_message {
  check_nhs_service
  node scripts/send-canary-update.js $(npm outdated --parseable)
}

function configure_hangout_webhook {
  export GOOGLE_CHAT_CANARY_WEBHOOK=$(get_aws_ssm_secret "/repo/prod/user-input/external/gocd-google-chat-canary-webhook")
  if [ -z "${GOOGLE_CHAT_CANARY_WEBHOOK}" ]; then
    echo "Unable to obtain GOOGLE_CHAT_CANARY_WEBHOOK from AWS"
    exit 5
  fi
}

###########
# Testing #
###########

function test_functional {
  check_env
  npm install
  if [[ $NHS_ENVIRONMENT == "dev" ]]; then
    npm run test:health
  else
    npm run test:functional
  fi
}

###########
## TASKS ##
###########

command="$1"
case "${command}" in
  _dep)
      npm install
      npm audit
      ;;
  dep)
      dojo "./tasks _dep"
      ;;
  _list_outdated)
      npm install
      npm outdated > outdated-dependencies.txt || send_canary_update_message
      ;;
  list_outdated)
      configure_hangout_webhook
      dojo "./tasks _list_outdated"
      ;;
  update_package_json)
      dojo "npx npm-check-updates -u"
      ;;
  send_dead_canary_message)
      check_nhs_service
      configure_hangout_webhook
      dojo "node scripts/send-canary-error.js"
      ;;
  _test_lint)
      npm install
      npm run lint
      ;;
  test_lint)
      dojo "./tasks _test_lint"
      ;;
  _test_unit)
      npm install
      npm run test:unit
      ;;
  test_unit)
      dojo "./tasks _test_unit"
      ;;
  _setup_test_integration_local)
      configure_local_envs
      npm run db:migrate
      prepare_local_envs_for_ide
      ;;
  _test_integration)
      npm install
      npm run db:migrate
      npm run test:integration
      npm run db:teardown
      ;;
  test_integration)
      configure_local_envs
      dojo -c Dojofile-itest "./tasks _test_integration"
      ;;
  _test_functional)
      test_functional
      ;;
  test_functional)
      configure_service_url
      dojo "./tasks _test_functional"
      ;;
  _test_coverage)
      npm install
      npm run db:migrate
      npm run test:coverage
      ;;
  test_coverage)
      configure_local_envs
      dojo -c Dojofile-itest "./tasks _test_coverage"
      ;;
  _build)
      rm -rf build
      npm install
      npm run build
      ;;
  build)
      dojo "./tasks _build"
      ;;
  build_docker_local)
      configure_local_envs
      build_docker_image
      ;;
  build_docker)
      configure_docker_repository_uri
      build_docker_image
      echo "Pushing the Docker image... $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG"
      docker push $REPOSITORY_URI:$IMAGE_TAG
      docker push $REPOSITORY_URI:latest
      ;;
  _test_docker)
      npm install
      npm run test:docker
      ;;
  test_docker)
      configure_local_envs
      configure_docker_repository_uri
      dojo -c Dojofile-dtest "./tasks _test_docker"
      ;;
  test_docker_local)
      configure_local_envs
      dojo -c Dojofile-dtest "./tasks _test_docker"
      ;;
  run_docker_local)
      configure_local_envs
      dojo -c Dojofile-dtest
      ;;
  _tf_plan)
      _assume_environment_role $NHS_ENVIRONMENT
      tf_plan "$2"
      ;;
  tf_plan)
      check_env
      dojo -c Dojofile-infra "./tasks _tf_plan $2"
      ;;
  _tf_plan_db_roles)
      _assume_environment_role $NHS_ENVIRONMENT
      tf_plan_db_roles "$2"
      ;;
  tf_plan_db_roles)
      check_env
      dojo -c Dojofile-infra "./tasks _tf_plan_db_roles $2"
      ;;
  _tf_plan_certs)
      _assume_environment_role $NHS_ENVIRONMENT
      tf_plan "$2" true
      ;;
  tf_plan_certs)
      check_env
      dojo -c Dojofile-infra "./tasks _tf_plan_certs $2"
      ;;
  _tf_apply)
      _assume_environment_role $NHS_ENVIRONMENT
      tf_apply
      ;;
  tf_apply)
      check_env
      dojo -c Dojofile-infra "./tasks _tf_apply"
      ;;
  _tf_apply_db_roles)
      _assume_environment_role $NHS_ENVIRONMENT
      tf_apply_db_roles
      ;;
  tf_apply_db_roles)
      check_env
      dojo -c Dojofile-infra "./tasks _tf_apply_db_roles"
      ;;
  _run_db_migrations)
      _assume_environment_role $NHS_ENVIRONMENT
      configure_db_migration_envs
      scripts/migrate-db.sh
      ;;
  run_db_migrations)
      check_env
      dojo -c Dojofile "./tasks _run_db_migrations"
      ;;
  promote_docker_image)
      check_env
      set_image_tag
      promote_docker_image "$IMAGE_REPO_NAME:$IMAGE_TAG" "$NHS_ENVIRONMENT"
      ;;
  _wait_ecs)
      _assume_environment_role $NHS_ENVIRONMENT
      aws ecs wait services-stable \
        --region $AWS_DEFAULT_REGION \
        --cluster $NHS_ENVIRONMENT-${NHS_SERVICE}-ecs-cluster \
        --service $NHS_ENVIRONMENT-${NHS_SERVICE}-service
      ;;
  wait_ecs)
      check_env
      dojo -c Dojofile-infra "./tasks _wait_ecs"
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
