format_version: 4
pipelines:
  ehr-out-service.audit:
    group: repo-audit
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
        ignore:
          - docs/**/*.*
    timer:
      spec: 0 0 8 ? * MON,TUE,WED,THU,FRI *
    stages:
      - audit:
          clean_workspace: true
          approval: manual
          jobs:
            dependency_check:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dep
