format_version: 4
common:
  deploy_job: &deploy_job
    resources:
      - docker
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks create_secrets
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan_certs create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan_db_roles create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply_db_roles
      # Applies permissions for migration_role
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks grant_db_permissions
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks run_db_migrations
      # Applies permissions for application_role for tables created during migration
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks grant_db_permissions
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs
  common_stages: &common_stages
    - promote_docker_image:
        resources:
          - docker
        clean_workspace: true
        tasks:
          - exec:
              command: /bin/bash
              arguments:
                - -c
                - ./tasks promote_docker_image
    - deploy:
        clean_workspace: true
        jobs:
          deploy: *deploy_job
    - functional:
        clean_workspace: true
        jobs:
          test:
            resources:
              - docker
            tasks:
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks test_functional
pipelines:
  'prm-deductions-repo-to-gp.dev':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      app:
        pipeline: prm-deductions-repo-to-gp
        stage: test_docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages: *common_stages
  'prm-deductions-repo-to-gp.test':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_test
    environment_variables:
      NHS_ENVIRONMENT: test
    stages: *common_stages
  'prm-deductions-repo-to-gp.perf':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_perf
    environment_variables:
      NHS_ENVIRONMENT: perf
    stages: *common_stages
  'prm-deductions-repo-to-gp.pre-prod':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_pre_prod
    environment_variables:
      NHS_ENVIRONMENT: pre-prod
    stages: *common_stages
